DROP TABLE MESSAGES;
DROP TABLE NOTIFICATIONS;
DROP TABLE CATEGORIES;




CREATE TABLE IF NOT EXISTS CATEGORIES(CATEGORY_ID SERIAL NOT NULL PRIMARY KEY, NAME VARCHAR(256) NOT NULL);
CREATE TABLE IF NOT EXISTS MESSAGES(MESSAGE_ID SERIAL NOT NULL PRIMARY KEY, MESSAGE TEXT NOT NULL, URL VARCHAR(512) NOT NULL, CATEGORY_ID INTEGER, CREATED_AT TIMESTAMP NOT NULL, 
CONSTRAINT CONST_CAT_MESSAGE FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORIES);
CREATE TABLE IF NOT EXISTS NOTIFICATIONS(NOTIFICATION_ID SERIAL NOT NULL PRIMARY KEY, NOTIFICATION TEXT NOT NULL, URL VARCHAR(512) NOT NULL, CATEGORY_ID INTEGER, CREATED_AT TIMESTAMP NOT NULL, 
CONSTRAINT CONST_CAT_NOTIFICATIONS FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORIES);

/*SEM CHAVE ESTRANGEIRA*/
CREATE TABLE IF NOT EXISTS CATEGORIES(CATEGORY_ID SERIAL NOT NULL PRIMARY KEY, NAME VARCHAR(256) NOT NULL);
CREATE TABLE IF NOT EXISTS MESSAGES(MESSAGE_ID SERIAL NOT NULL PRIMARY KEY, MESSAGE TEXT NOT NULL, URL VARCHAR(512) NOT NULL, CREATED_AT TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS NOTIFICATIONS(NOTIFICATION_ID SERIAL NOT NULL PRIMARY KEY, NOTIFICATION TEXT NOT NULL, URL VARCHAR(512) NOT NULL, CREATED_AT TIMESTAMP NOT NULL);

