/*DROP TABLE MESSAGES;
DROP TABLE NOTIFICATIONS;
DROP TABLE CATEGORIES;*/

CREATE TABLE IF NOT EXISTS CATEGORIES(CATEGORY_ID SERIAL NOT NULL PRIMARY KEY, NAME VARCHAR(256) NOT NULL);
CREATE TABLE IF NOT EXISTS MESSAGES(MESSAGE_ID SERIAL NOT NULL PRIMARY KEY, MESSAGE TEXT NOT NULL, URL VARCHAR(32) NOT NULL UNIQUE, URL_REDIRECT VARCHAR(512) NOT NULL, CREATED_AT TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS NOTIFICATIONS(NOTIFICATION_ID SERIAL NOT NULL PRIMARY KEY, NOTIFICATION TEXT NOT NULL, URL VARCHAR(32) NOT NULL UNIQUE, URL_REDIRECT VARCHAR(512) NOT NULL, CATEGORY_ID INTEGER, CREATED_AT TIMESTAMP NOT NULL, 
CONSTRAINT CONST_CAT_NOTIFICATIONS FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORIES);
CREATE TABLE IF NOT EXISTS REPORTS(REPORT_ID SERIAL NOT NULL PRIMARY KEY, USER_IP VARCHAR(48), USER_AGENT VARCHAR(256), URL VARCHAR(32) NOT NULL, DATE_TIME TIMESTAMP NOT NULL); 


/*SEM CHAVE ESTRANGEIRA*/
/*CREATE TABLE IF NOT EXISTS CATEGORIES(CATEGORY_ID SERIAL NOT NULL PRIMARY KEY, NAME VARCHAR(256) NOT NULL);
CREATE TABLE IF NOT EXISTS MESSAGES(MESSAGE_ID SERIAL NOT NULL PRIMARY KEY, MESSAGE TEXT NOT NULL, URL VARCHAR(512) NOT NULL, CREATED_AT TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS NOTIFICATIONS(NOTIFICATION_ID SERIAL NOT NULL PRIMARY KEY, NOTIFICATION TEXT NOT NULL, URL VARCHAR(512) NOT NULL, CREATED_AT TIMESTAMP NOT NULL);
*/